export { CloudTrailAudit } from './audit.js';
export { ElastiCacheRedis } from './cache.js';
export { CloudFrontCdn } from './cdn.js';
export { SesEmail } from './email.js';
export { CognitoIdentity } from './identity.js';
export { SnsMessaging } from './messaging.js';
export { CloudWatchMonitoring } from './monitoring.js';
export { ParameterStore } from './parameters.js';
export { SqsQueue } from './queue.js';
export { OpenSearchAws } from './search.js';
export { SecretsManager } from './secrets.js';
export { S3Storage } from './storage.js';
export { KinesisStreaming, MskStreaming } from './streaming.js';
