import { CdnManagementClient, type AFDEndpoint, type AFDEndpointUpdateParameters } from '@azure/arm-cdn';

import { UnsupportedError, wrapProviderError } from '../../errors.js';
import type { AzureCredentials } from '../../credentials/index.js';
import type { Cdn, CdnDistribution, CdnDistributionOptions, CdnInvalidation } from '../types/cdn.js';
import { azureCredential } from './auth.js';

const ORIGIN_DOMAIN_TAG_KEY = 'fc-origin-domain';

function uniqueRef(): string {
  return `${process.hrtime.bigint()}`;
}

function toCdnDistribution(ep: AFDEndpoint | undefined): CdnDistribution {
  const out: CdnDistribution = { id: '', domainName: '', originDomain: '', status: '', enabled: false, comment: '' };
  if (!ep) return out;
  out.id = ep.name ?? '';
  out.domainName = ep.hostName ?? '';
  out.status = ep.deploymentStatus ?? ep.provisioningState ?? '';
  out.enabled = ep.enabledState === 'Enabled';
  const originDomain = ep.tags?.[ORIGIN_DOMAIN_TAG_KEY];
  if (originDomain) out.originDomain = originDomain;
  return out;
}

/** Azure Front Door implementation of the unified CDN interface; distributions map to AFD endpoints. */
export class FrontDoorCdn implements Cdn {
  private readonly endpoints: CdnManagementClient['afdEndpoints'];
  private readonly resourceGroup: string;
  private readonly profileName: string;

  constructor(creds: AzureCredentials, resourceGroup: string, profileName: string) {
    const client = new CdnManagementClient(azureCredential(creds), creds.subscriptionId);
    this.endpoints = client.afdEndpoints;
    this.resourceGroup = resourceGroup;
    this.profileName = profileName;
  }

  async createDistribution(opts: CdnDistributionOptions): Promise<CdnDistribution> {
    const name = `fc-${uniqueRef()}`;
    const endpoint: AFDEndpoint = {
      location: 'Global',
      enabledState: opts.enabled ? 'Enabled' : 'Disabled',
      autoGeneratedDomainNameLabelScope: 'TenantReuse',
      tags: { [ORIGIN_DOMAIN_TAG_KEY]: opts.originDomain },
    };
    try {
      const poller = this.endpoints.create(this.resourceGroup, this.profileName, name, endpoint);
      const result = await poller.pollUntilDone();
      return toCdnDistribution(result);
    } catch (err) {
      return wrapProviderError('azure', 'createDistribution', err);
    }
  }

  async getDistribution(id: string): Promise<CdnDistribution> {
    try {
      const ep = await this.endpoints.get(this.resourceGroup, this.profileName, id);
      return toCdnDistribution(ep);
    } catch (err) {
      return wrapProviderError('azure', 'getDistribution', err);
    }
  }

  async listDistributions(): Promise<CdnDistribution[]> {
    const results: CdnDistribution[] = [];
    try {
      for await (const ep of this.endpoints.listByProfile(this.resourceGroup, this.profileName)) {
        results.push(toCdnDistribution(ep));
      }
    } catch (err) {
      return wrapProviderError('azure', 'listDistributions', err);
    }
    return results;
  }

  async updateDistribution(id: string, opts: CdnDistributionOptions): Promise<CdnDistribution> {
    const params: AFDEndpointUpdateParameters = {
      enabledState: opts.enabled ? 'Enabled' : 'Disabled',
      tags: { [ORIGIN_DOMAIN_TAG_KEY]: opts.originDomain },
    };
    try {
      const poller = this.endpoints.update(this.resourceGroup, this.profileName, id, params);
      const result = await poller.pollUntilDone();
      return toCdnDistribution(result);
    } catch (err) {
      return wrapProviderError('azure', 'updateDistribution', err);
    }
  }

  async deleteDistribution(id: string): Promise<void> {
    try {
      const poller = this.endpoints.delete(this.resourceGroup, this.profileName, id);
      await poller.pollUntilDone();
    } catch (err) {
      wrapProviderError('azure', 'deleteDistribution', err);
    }
  }

  private async setEnabled(id: string, enabled: boolean, op: string): Promise<void> {
    const params: AFDEndpointUpdateParameters = { enabledState: enabled ? 'Enabled' : 'Disabled' };
    try {
      const poller = this.endpoints.update(this.resourceGroup, this.profileName, id, params);
      await poller.pollUntilDone();
    } catch (err) {
      wrapProviderError('azure', op, err);
    }
  }

  async enableDistribution(id: string): Promise<void> {
    return this.setEnabled(id, true, 'enableDistribution');
  }

  async disableDistribution(id: string): Promise<void> {
    return this.setEnabled(id, false, 'disableDistribution');
  }

  async createInvalidation(id: string, paths: string[]): Promise<string> {
    try {
      const poller = this.endpoints.purgeContent(this.resourceGroup, this.profileName, id, { contentPaths: paths });
      await poller.pollUntilDone();
      return id;
    } catch (err) {
      return wrapProviderError('azure', 'createInvalidation', err);
    }
  }

  async getInvalidation(_id: string, _invalidationId: string): Promise<CdnInvalidation> {
    throw new UnsupportedError(
      'azure',
      'getInvalidation',
      'Azure Front Door purge status is not individually queryable',
      'Purge completes synchronously via createInvalidation',
    );
  }

  async listInvalidations(_id: string): Promise<CdnInvalidation[]> {
    throw new UnsupportedError(
      'azure',
      'listInvalidations',
      'Azure Front Door purge status is not individually queryable',
      'Purge completes synchronously via createInvalidation',
    );
  }
}
