import {
  constants,
  createDecipheriv,
  createCipheriv,
  createPublicKey,
  generateKeyPairSync,
  privateDecrypt,
  publicEncrypt,
  randomBytes,
  type KeyObject,
} from 'node:crypto';

import { FluidCloudError, ErrorCode, messageOf } from '../errors.js';

/**
 * Envelope encryption for secure credential transfer over HTTPS.
 *
 * Mirrors the Go SDK byte for byte:
 *   - the SDK generates an ephemeral RSA-2048 key pair per request
 *   - the server encrypts credentials with a random AES-256-GCM data encryption key (DEK)
 *   - the server wraps the DEK with the SDK public key using RSA-OAEP-SHA256
 *   - the SDK unwraps the DEK with its private key, then decrypts the credentials
 *
 * Even if TLS is compromised the credentials stay protected, because only this
 * process holds the ephemeral private key.
 */

const RSA_KEY_BITS = 2048;
const AES_KEY_BYTES = 32;
const GCM_NONCE_BYTES = 12;
const GCM_TAG_BYTES = 16;

/** Sent by the SDK to request encrypted credentials. */
export interface EnvelopeRequest {
  /** PEM-encoded ephemeral RSA public key generated by the SDK. */
  publicKey: string;
}

/** Returned by the server with the encrypted credential envelope. */
export interface EnvelopeResponse {
  provider: string;
  region: string;
  /** base64 AES-256-GCM ciphertext of the credentials JSON. */
  encryptedCredentials: string;
  /** base64 RSA-OAEP-SHA256 wrapped AES-256 data encryption key. */
  encryptedKey: string;
  /** base64 96-bit GCM nonce. */
  nonce: string;
}

/** An RSA key pair generated for a single credential fetch. */
export interface EphemeralKeyPair {
  privateKey: KeyObject;
  publicKey: KeyObject;
  /** PEM-encoded public key to send to the server. */
  publicKeyPem: string;
}

function envelopeError(message: string, cause?: unknown): FluidCloudError {
  const detail = cause === undefined ? message : `${message}: ${messageOf(cause)}`;
  return new FluidCloudError(detail, ErrorCode.InvalidCredentials, { cause });
}

/**
 * Creates a new RSA-2048 key pair for a single credential fetch. The pair is
 * ephemeral and should be discarded once the credentials are decrypted.
 */
export function generateEphemeralKeyPair(): EphemeralKeyPair {
  try {
    const { privateKey, publicKey } = generateKeyPairSync('rsa', { modulusLength: RSA_KEY_BITS });
    const publicKeyPem = publicKey.export({ type: 'spki', format: 'pem' }).toString();
    return { privateKey, publicKey, publicKeyPem };
  } catch (err) {
    throw envelopeError('failed to generate ephemeral RSA key pair', err);
  }
}

/**
 * Decrypts the server envelope with the ephemeral private key: unwraps the DEK
 * with RSA-OAEP-SHA256, then opens the AES-256-GCM ciphertext.
 */
export function decryptEnvelope(kp: EphemeralKeyPair, resp: EnvelopeResponse): Record<string, unknown> {
  const encryptedKey = decodeBase64(resp.encryptedKey, 'encrypted key');
  const nonce = decodeBase64(resp.nonce, 'nonce');
  const encryptedCreds = decodeBase64(resp.encryptedCredentials, 'encrypted credentials');

  let dek: Buffer;
  try {
    dek = privateDecrypt(
      { key: kp.privateKey, padding: constants.RSA_PKCS1_OAEP_PADDING, oaepHash: 'sha256' },
      encryptedKey,
    );
  } catch (err) {
    throw envelopeError('failed to unwrap data encryption key', err);
  }

  if (dek.length !== AES_KEY_BYTES) {
    throw envelopeError(`invalid data encryption key size: expected ${AES_KEY_BYTES}-byte DEK, got ${dek.length} bytes`);
  }
  if (nonce.length !== GCM_NONCE_BYTES) {
    throw envelopeError(`invalid nonce size: expected ${GCM_NONCE_BYTES}-byte nonce, got ${nonce.length} bytes`);
  }
  if (encryptedCreds.length < GCM_TAG_BYTES) {
    throw envelopeError('failed to decrypt credentials (authentication failed): ciphertext shorter than GCM tag');
  }

  // Go's gcm.Seal appends the 16-byte auth tag to the ciphertext; Node keeps
  // them separate, so the tail has to be split off before decrypting.
  const tag = encryptedCreds.subarray(encryptedCreds.length - GCM_TAG_BYTES);
  const body = encryptedCreds.subarray(0, encryptedCreds.length - GCM_TAG_BYTES);

  let plaintext: Buffer;
  try {
    const decipher = createDecipheriv('aes-256-gcm', dek, nonce);
    decipher.setAuthTag(tag);
    plaintext = Buffer.concat([decipher.update(body), decipher.final()]);
  } catch (err) {
    throw envelopeError('failed to decrypt credentials (authentication failed)', err);
  }

  try {
    return JSON.parse(plaintext.toString('utf8')) as Record<string, unknown>;
  } catch (err) {
    throw envelopeError('failed to parse decrypted credentials', err);
  }
}

/**
 * Encrypts credentials for transport using the SDK ephemeral public key. This is
 * the server-side half, kept here as a reference implementation and for tests.
 */
export function encryptEnvelope(
  publicKeyPem: string,
  credentials: Record<string, unknown>,
): { encryptedCredentials: string; encryptedKey: string; nonce: string } {
  const pubKey = parsePublicKeyPem(publicKeyPem);
  const dek = randomBytes(AES_KEY_BYTES);
  const nonce = randomBytes(GCM_NONCE_BYTES);

  const cipher = createCipheriv('aes-256-gcm', dek, nonce);
  const credsJson = Buffer.from(JSON.stringify(credentials), 'utf8');
  const ciphertext = Buffer.concat([cipher.update(credsJson), cipher.final(), cipher.getAuthTag()]);

  const wrappedDek = publicEncrypt(
    { key: pubKey, padding: constants.RSA_PKCS1_OAEP_PADDING, oaepHash: 'sha256' },
    dek,
  );

  return {
    encryptedCredentials: ciphertext.toString('base64'),
    encryptedKey: wrappedDek.toString('base64'),
    nonce: nonce.toString('base64'),
  };
}

/** Parses a PEM-encoded RSA public key. */
export function parsePublicKeyPem(publicKeyPem: string): KeyObject {
  let key: KeyObject;
  try {
    key = createPublicKey(publicKeyPem);
  } catch (err) {
    throw envelopeError('failed to decode PEM public key', err);
  }
  if (key.asymmetricKeyType !== 'rsa') throw envelopeError('public key is not RSA');
  return key;
}

function decodeBase64(value: string, field: string): Buffer {
  const buf = Buffer.from(value ?? '', 'base64');
  if (value && buf.length === 0) throw envelopeError(`failed to decode ${field}`);
  return buf;
}
